export const COUNT_PER_PAGE = 24;
export const BOOKS_HOME_POPULAR_ARTICLE_COUNT = 4;
export const ARTICLE_HOME_SECTION_COUNT = 4;
export const ARTICLE_HOME_RECENT_SECTION_COUNT = 8;
export const ARTICLE_HOME_CHART_SECTION_COUNT = 20;
export const ARTICLE_CHART_COUNT = 100;
